### ISSUE TITLE
Redis request doesn't receive the device validation callback response

### ISSUE THREAD

**Issue by weichou1229** [edgexfoundry/go-mod-messaging#227] opened 2023-03-06 08:29 UTC
# 🐞 Bug Report

### Affected Services [**REQUIRED**]

 The issue is located in go-mod-messaging

### Is this a regression?

 No

### Description and Minimal Reproduction [**REQUIRED**]
- Run redis
  - `docker run --rm --name redis -p 6379:6379 -d redis:7.0-alpine redis-server`
- Run core-metadata service and device-virtual
- Invoke device adding request several time
- core-metadata throws a timeout error

The core-metadata seems doesn't receive the response from the device-virtual. This error occur in the edgex-taf test, I also tried to use source code with the latest change of `go-mod-messaging` but the error still happens.

## 🔥 Exception or Error
core-metadata logs
```
level=ERROR ts=2023-03-06T09:03:53.052675Z app=core-metadata source=device.go:67 X-Correlation-ID=ec7c3639-c772-4734-b597-a97d499159e0 msg="Error sending request to topic 'edgex/device-virtual/validate/device' -> timed out waiting for response on edgex/response/device-virtual/aea88ce9-ec29-4903-a420-0256c427fdb0 topic"
level=ERROR ts=2023-03-06T09:03:53.052734Z app=core-metadata source=encoding.go:32 msg="Error encoding the data: http: Handler timeout"
```
device-virtual logs:
```
level=DEBUG ts=2023-03-06T09:03:48.050612Z app=device-virtual source=validation.go:58 msg="Device validation request received on message queue. Topic: edgex/device-virtual/validate/device, Correlation-id: 17633746-f200-4481-b20e-a3d7a8b74af9"
level=DEBUG ts=2023-03-06T09:03:48.051873Z app=device-virtual source=validation.go:100 msg="Device validation response published on message queue. Topic: edgex/response/device-virtual/aea88ce9-ec29-4903-a420-0256c427fdb0, Correlation-id: 17633746-f200-4481-b20e-a3d7a8b74af9"
```

## 🌍  Your Environment
**Deployment Environment:**
MacOS

**EdgeX Version [**REQUIRED**]:**
Main branch

**Anything else relevant?**

**Comment by cloudxxx8** [comment] 2023-03-06 08:33
I assume your test is based on Redis Pub/Sub, and it might be fixed by this PR
https://github.com/edgexfoundry/go-mod-messaging/pull/226

Could you please verify with the latest go-mod-messaging?

**Comment by weichou1229** [comment] 2023-03-06 08:51
Yes, I tested it on Redis Pub/Sub and verified it with the latest go-mod-messaging, and the error still happens sometime.

**Comment by weichou1229** [comment] 2023-03-07 03:48
@lenny-intel I pulled the latest changes from the edgex-go and go-mod-messaging, but still got the same error when I invoke the device adding request several times.

core-metadata logs:
```
level=DEBUG ts=2023-03-07T03:45:42.686157Z app=core-metadata source=notify.go:49 msg="Sending Device Validation request for device=testDevice, CorrelationId=ae4a5b28-713d-43d3-9589-0a3df0479281 to topic: edgex/device-virtual/validate/device"
level=DEBUG ts=2023-03-07T03:45:42.686181Z app=core-metadata source=notify.go:50 msg="Waiting for Device Validation response on topic: edgex/response/device-virtual/93075827-6489-4393-8e9b-68523faf93b6"
level=ERROR ts=2023-03-07T03:45:47.690472Z app=core-metadata source=device.go:67 X-Correlation-ID=328aac88-5421-4c1c-8b02-24ab62a62349 msg="Error sending request to topic 'edgex/device-virtual/validate/device' -> timed out waiting for response on edgex/response/device-virtual/93075827-6489-4393-8e9b-68523faf93b6 topic"
level=DEBUG ts=2023-03-07T03:45:47.690514Z app=core-metadata source=device.go:68 X-Correlation-ID=328aac88-5421-4c1c-8b02-24ab62a62349 msg="[/Users/bruce/Documents/weichou/edgex-go/internal/core/metadata/application/device.go]-github.com/edgexfoundry/edgex-go/internal/core/metadata/application.AddDevice(line 44):  -> [/Users/bruce/Documents/weichou/edgex-go/internal/core/metadata/application/notify.go]-github.com/edgexfoundry/edgex-go/internal/core/metadata/application.validateDeviceCallback(line 54): Error sending request to topic 'edgex/device-virtual/validate/device' -> timed out waiting for response on edgex/response/device-virtual/93075827-6489-4393-8e9b-68523faf93b6 topic"
level=ERROR ts=2023-03-07T03:45:47.690542Z app=core-metadata source=encoding.go:32 msg="Error encoding the data: http: Handler timeout"


```
device-virtual logs:
```
level=DEBUG ts=2023-03-07T03:45:42.688218Z app=device-virtual source=validation.go:58 msg="Device validation request received on message queue. Topic: edgex/device-virtual/validate/device, Correlation-id: ae4a5b28-713d-43d3-9589-0a3df0479281"
level=DEBUG ts=2023-03-07T03:45:42.68923Z app=device-virtual source=validation.go:100 msg="Device validation response published on message queue. Topic: edgex/response/device-virtual/93075827-6489-4393-8e9b-68523faf93b6, Correlation-id: ae4a5b28-713d-43d3-9589-0a3df0479281"
```

**Comment by lenny-intel** [comment] 2023-03-07 20:55
@weichou1229 , it is Core Metadata latest that is required as it is the one using the Request API to validate devices. Add devices is working fine with Redis Pub/Sub with latest images. I have seen some issues from App Service sending many Requests that I hope recent optimization PR resolves. 

My current App Service commanding test is running well.

**Comment by weichou1229** [comment] 2023-03-08 01:38
@lenny-intel 
I can reproduce the error by sending many requests too, 
>  I have seen some issues from App Service sending many Requests that I hope recent optimization PR resolves.

and I still see the timeout error on today's [edgex-taf function-test report](https://jenkins.edgexfoundry.org/view/EdgeX%20Foundry%20Project/job/edgexfoundry/job/edgex-taf-pipelines/job/functional-test/1189/), might need to wait for the docker image update.

**Comment by lenny-intel** [comment] 2023-03-08 15:59
@weichou1229 , please confirm if you are still see this issue.

**Comment by weichou1229** [comment] 2023-03-09 02:29
@lenny-intel I still see the issue in the edgex-taf test.

I also recreate the issue with the source code, the issue happens when the device-virtual started and I send the device adding request 
```
level=DEBUG ts=2023-03-09T02:23:16.931988Z app=core-metadata source=notify.go:50 msg="Waiting for Device Validation response on topic: edgex/response/device-virtual/5ad223a3-8cdb-4f19-8583-4331d41ce760"
level=ERROR ts=2023-03-09T02:23:21.936346Z app=core-metadata source=device.go:67 X-Correlation-ID=17aae5fa-b6a4-42df-be26-d3f0f477bde3 msg="Error sending request to topic 'edgex/device-virtual/validate/device' -> timed out waiting for response on edgex/response/device-virtual/5ad223a3-8cdb-4f19-8583-4331d41ce760 topic"
level=DEBUG ts=2023-03-09T02:23:21.936382Z app=core-metadata source=device.go:68 X-Correlation-ID=17aae5fa-b6a4-42df-be26-d3f0f477bde3 msg="[/Users/bruce/Documents/weichou/edgex-go/internal/core/metadata/application/device.go]-github.com/edgexfoundry/edgex-go/internal/core/metadata/application.AddDevice(line 44):  -> [/Users/bruce/Documents/weichou/edgex-go/internal/core/metadata/application/notify.go]-github.com/edgexfoundry/edgex-go/internal/core/metadata/application.validateDeviceCallback(line 54): Error sending request to topic 'edgex/device-virtual/validate/device' -> timed out waiting for response on edgex/response/device-virtual/5ad223a3-8cdb-4f19-8583-4331d41ce760 topic"
level=ERROR ts=2023-03-09T02:23:21.936409Z app=core-metadata source=encoding.go:32 msg="Error encoding the data: http: Handler timeout"
```

**Comment by lenny-intel** [comment] 2023-03-14 00:03
@weichou1229 , I just ran this use case with Device REST, using the UI to add a device.

No errors reported by Core Metadata
Logs from Device REST show the device was added:
```
level=DEBUG ts=2023-03-13T23:59:21.6239054Z app=device-rest source=validation.go:58 msg="Device validation request received on message queue. Topic: edgex/device-rest/validate/device, Correlation-id: 3a168512-f739-4b63-8638-c9a132d74610"
level=DEBUG ts=2023-03-13T23:59:21.6248986Z app=device-rest source=validation.go:100 msg="Device validation response published on message queue. Topic: edgex/response/device-rest/82a268b4-1944-4d1f-9542-0cbac7f3e01a, Correlation-id: 3a168512-f739-4b63-8638-c9a132d74610"
level=DEBUG ts=2023-03-13T23:59:21.626467Z app=device-rest source=callback.go:58 msg="System event received on message queue. Topic: edgex/system-events/core-metadata/device/add/device-rest/sample-numeric, Correlation-id: bf1c1024-4dbb-47a1-aa30-bd53c76c9757"
level=DEBUG ts=2023-03-13T23:59:21.6284684Z app=device-rest source=callback.go:70 msg="device snum added"
level=DEBUG ts=2023-03-13T23:59:21.628522Z app=device-rest source=callback.go:75 msg="Invoked driver.AddDevice callback for snum"
level=DEBUG ts=2023-03-13T23:59:21.6285368Z app=device-rest source=callback.go:81 msg="starting AutoEvents for device snum"

```
UI shows the device was successfully added
![image](https://user-images.githubusercontent.com/44779287/224858432-3fcf0a1a-975c-46df-8cac-6b453433d6b6.png)
![image](https://user-images.githubusercontent.com/44779287/224858479-8e61141f-ae83-4d9c-9038-e61a47a36de6.png)

**Comment by weichou1229** [comment] 2023-03-14 07:32
@lenny-intel  I thought it was much better than before, but I still get the timeout error sometimes.

```
level=DEBUG ts=2023-03-14T07:25:16.735152Z app=core-metadata source=notify.go:49 msg="Sending Device Validation request for device=testDevice, CorrelationId=4be80417-dd7f-4ce3-8257-6b20d66bf3c9 to topic: edgex/device-virtual/validate/device"
level=DEBUG ts=2023-03-14T07:25:16.735173Z app=core-metadata source=notify.go:50 msg="Waiting for Device Validation response on topic: edgex/response/device-virtual/f25fc488-e617-47c6-b594-2833d309b149"
level=ERROR ts=2023-03-14T07:25:21.740151Z app=core-metadata source=device.go:67 X-Correlation-ID=36d50c80-8138-4b93-bb43-f315d2b8df1c msg="Error sending request to topic 'edgex/device-virtual/validate/device' -> timed out waiting for response on edgex/response/device-virtual/f25fc488-e617-47c6-b594-2833d309b149 topic"
level=DEBUG ts=2023-03-14T07:25:21.74019Z app=core-metadata source=device.go:68 X-Correlation-ID=36d50c80-8138-4b93-bb43-f315d2b8df1c msg="[/Users/bruce/Documents/weichou/edgex-go/internal/core/metadata/application/device.go]-github.com/edgexfoundry/edgex-go/internal/core/metadata/application.AddDevice(line 44):  -> [/Users/bruce/Documents/weichou/edgex-go/internal/core/metadata/application/notify.go]-github.com/edgexfoundry/edgex-go/internal/core/metadata/application.validateDeviceCallback(line 54): Error sending request to topic 'edgex/device-virtual/validate/device' -> timed out waiting for response on edgex/response/device-virtual/f25fc488-e617-47c6-b594-2833d309b149 topic"
level=ERROR ts=2023-03-14T07:25:21.740222Z app=core-metadata source=encoding.go:32 msg="Error encoding the data: http: Handler timeout"
```

```
level=DEBUG ts=2023-03-14T07:25:16.737557Z app=device-virtual source=validation.go:58 msg="Device validation request received on message queue. Topic: edgex/device-virtual/validate/device, Correlation-id: 4be80417-dd7f-4ce3-8257-6b20d66bf3c9"
level=DEBUG ts=2023-03-14T07:25:16.73887Z app=device-virtual source=validation.go:100 msg="Device validation response published on message queue. Topic: edgex/response/device-virtual/f25fc488-e617-47c6-b594-2833d309b149, Correlation-id: 4be80417-dd7f-4ce3-8257-6b20d66bf3c9"
```

**Comment by cloudxxx8** [comment] 2023-04-10 06:34
@lenny-intel this issue still happens from time to time.  do you have resource to investigate this or should I assign someone from my team to work on this?

**Comment by cloudxxx8** [comment] 2023-04-10 06:44
Since MQTT works fine, there might be something wrong in the Redis pub/sub implementation

**Comment by lenny-intel** [comment] 2023-04-10 15:53
> @lenny-intel this issue still happens from time to time. do you have resource to investigate this or should I assign someone from my team to work on this?

@cloudxxx8 , When are we seeing this? It has been working for me in all my testing of bootstrapping device services and adding new devices via the UI. 

I think it is time to have another set of eyes on this one. 

The [subscribe step](https://github.com/edgexfoundry/go-mod-messaging/blob/main/internal/pkg/request.go#L55) of the Request API must be completed prior to the [Publish step](https://github.com/edgexfoundry/go-mod-messaging/blob/main/internal/pkg/request.go#L66). For the Redis implementation, I have put in Wait Group to ensure the [underlying Subscribe has completed](https://github.com/edgexfoundry/go-mod-messaging/blob/main/internal/pkg/redis/client.go#L201) before the Subscribe interface returns.

The other scenario where we could get a timeout is the target service (Device Service) is not properly subscribed to the Request topic. We need to verify the target service is receiving the Request and Publishing a response on the expected topic.

**Comment by weichou1229** [comment] 2023-04-11 03:48
This issue can be recreated by invoking device addition API in short intervals.

The steps for recreating the issue:
1. Run core service and device virtual
2. Run script 
```
#!/bin/sh

for i in {1..10}
do
   curl 'http://localhost:59881/api/v2/device' --header 'Content-Type: application/json' \
     --data '[
       {
         "apiVersion": "v2",
         "device": {
           "name": "testDevice",
           "description": "Home automation system",
           "adminState": "UNLOCKED",
           "operatingState": "UNKNOWN",
           "serviceName": "device-virtual",
           "profileName": "Random-UnsignedInteger-Device",
           "protocols": {
             "other": {
               "Address": "device-virtual-uint-01",
               "Protocol": "300"
             }
           }
         }
       }
     ]'
   echo 'wait for 0.5s'
   sleep .5
done
```
3. the output shown as below
```
$ sh test.sh 
HTTP request timeoutwait for 0.5s
[{"apiVersion":"v2","message":"device name testDevice already exists","statusCode":409}]
wait for 0.5s
HTTP request timeoutwait for 0.5s
[{"apiVersion":"v2","message":"device name testDevice already exists","statusCode":409}]
wait for 0.5s
[{"apiVersion":"v2","message":"device name testDevice already exists","statusCode":409}]
wait for 0.5s
[{"apiVersion":"v2","message":"device name testDevice already exists","statusCode":409}]
wait for 0.5s
[{"apiVersion":"v2","message":"device name testDevice already exists","statusCode":409}]
wait for 0.5s
HTTP request timeoutwait for 0.5s
HTTP request timeoutwait for 0.5s
[{"apiVersion":"v2","message":"device name testDevice already exists","statusCode":409}]
wait for 0.5s
```

The `HTTP request timeout` happens sometimes.

**Comment by lenny-intel** [comment] 2023-04-12 23:37
@hahattan , I am unable to recreate this with script. I modified it to run for ever and got to almost 200 iterations w/o error

```
i=1
while :
do
  echo $i
   curl 'http://localhost:59881/api/v2/device' --header 'Content-Type: application/json' \
     --data '[
       {
         "apiVersion": "v2",
         "device": {
           "name": "testDevice",
           "description": "Home automation system",
           "adminState": "UNLOCKED",
           "operatingState": "UNKNOWN",
           "serviceName": "device-virtual",
           "profileName": "Random-UnsignedInteger-Device",
           "protocols": {
             "other": {
               "Address": "device-virtual-uint-01",
               "Protocol": "300"
             }
           }
         }
       }
     ]'
   echo 'wait for 0.5s'
   sleep .5
   i=$((i+1))
done
```

I tested it using this [compose file](https://github.com/edgexfoundry/edgex-compose/blob/main/docker-compose-no-secty.yml) 
By running the following from edgex-compose top folder
 - `make pull no-secty`
 - `make run no-secty`

**Comment by hahattan** [comment] 2023-04-13 07:26
For the record this error is only viable if running `core-metadata` from source-code. 
(I cannot reproduce this running `core-metadata` in Docker container)

How I recreate this:
1. Run `consul`, `database`, `core-common-config-bootstrapper` from edgex-compose
2. Run `core-metadata` and `device-simple` from source code
3. Run the script provided by @lenny-intel 

Error log:
```
level=ERROR ts=2023-04-13T07:20:30.598854Z app=core-metadata source=device.go:67 X-Correlation-ID=65203104-181c-4ecc-be55-249bde5b0612 msg="Error sending request to topic 'edgex/device-simple/validate/device' -> timed out waiting for response on edgex/response/device-simple/c4e38367-829a-4dc8-adc0-254676b2516d topic"
level=DEBUG ts=2023-04-13T07:20:30.598892Z app=core-metadata source=device.go:68 X-Correlation-ID=65203104-181c-4ecc-be55-249bde5b0612 msg="[/Users/chris/Workspace/EdgeX/edgex-go/internal/core/metadata/application/device.go]-github.com/edgexfoundry/edgex-go/internal/core/metadata/application.AddDevice(line 52):  -> [/Users/chris/Workspace/EdgeX/edgex-go/internal/core/metadata/application/notify.go]-github.com/edgexfoundry/edgex-go/internal/core/metadata/application.validateDeviceCallback(line 54): Error sending request to topic 'edgex/device-simple/validate/device' -> timed out waiting for response on edgex/response/device-simple/c4e38367-829a-4dc8-adc0-254676b2516d topic"
level=ERROR ts=2023-04-13T07:20:30.598923Z app=core-metadata source=encoding.go:33 msg="Error encoding the data: http: Handler timeout"

```

**Comment by lenny-intel** [comment] 2023-04-13 16:35
> For the record this error is only viable if running `core-metadata` from source-code.
> (I cannot reproduce this running `core-metadata` in Docker container)

That is strange! I will confirm on my system.

> I modified this function:

That is interesting. Receive() is suppose to block and this would case the Subscribe to not return as expected or loose the first message. So is the first Receive() not blocking in this case and returning the subscription?? And why is this not an issue in Docker?

Also, note the description for Receive(). Should we try switching to Channel?

```
// Receive returns a message as a Subscription, Message, Pong or error.
// See PubSub example for details. This is low-level API and in most cases
// Channel should be used instead.
```

**Comment by hahattan** [comment] 2023-04-13 17:29
> That is interesting. Receive() is suppose to block and this would case the Subscribe to not return as expected or loose the first message. So is the first Receive() not blocking in this case and returning the subscription?? And why is this not an issue in Docker?
> 

It should be blocking until redis [returning the confirmation](https://redis.io/commands/psubscribe/#return) right ?
And then the following `ReceivedMessage` is able to receive response correctly:
https://github.com/edgexfoundry/go-mod-messaging/blob/be60aface920d4f7c2da099a9e11fc85920e2a52/internal/pkg/redis/goredis.go#L95-L98

Really have no idea why this is not seen in Docker ...

> Also, note the description for Receive(). Should we try switching to Channel?
> 
> ```
> // Receive returns a message as a Subscription, Message, Pong or error.
> // See PubSub example for details. This is low-level API and in most cases
> // Channel should be used instead.
> ```

Yes maybe switching to `Channel` can solve this but requires some refactoring

**Comment by lenny-intel** [comment] 2023-04-13 20:41
> Yes maybe switching to `Channel` can solve this but requires some refactoring

Yep, IMO not something we want to do this late in he dev cycle. I am ok with the above work around.

**Comment by lenny-intel** [comment] 2023-04-13 22:54
I also confirmed 23045 iterations w/o error with Core Metadata running in Docker.

**Closed** 2023-04-14 20:58 UTC
Labels: bug, 3-high
